#!/usr/bin/env bash
# Homebrew: ensure it is installed and on PATH, then install packages in two
# waves — essentials first (so dotfiles can be set up), then everything else.

# Ensure Homebrew is installed and its environment is loaded into this shell.
ensure_homebrew() {
  # Detect an existing install even if `brew` isn't on PATH yet (a fresh install
  # only adds itself to PATH for *new* shells). Check the known prefixes too.
  local brew_bin=""
  if command -v brew >/dev/null 2>&1; then
    brew_bin="$(command -v brew)"
  elif [ -x /opt/homebrew/bin/brew ]; then
    brew_bin=/opt/homebrew/bin/brew      # Apple Silicon
  elif [ -x /usr/local/bin/brew ]; then
    brew_bin=/usr/local/bin/brew         # Intel
  fi

  if [ -n "$brew_bin" ]; then
    info "Homebrew already installed ($brew_bin)"
  elif [ "${DRY_RUN:-false}" = "true" ]; then
    section "Installing Homebrew"
    # Don't fetch the installer over the network during a dry run.
    printf '%s  [dry-run] install Homebrew via the official install.sh%s\n' \
      "$_C_YELLOW" "$_C_RESET"
  else
    section "Installing Homebrew"
    info "Homebrew's installer will ask for your password and a RETURN to continue."
    # Run interactively (no NONINTERACTIVE): the installer prompts for your sudo
    # password itself. NONINTERACTIVE mode would instead require passwordless sudo.
    /bin/bash -c \
      "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # Resolve the binary the installer just placed.
    [ -x /opt/homebrew/bin/brew ] && brew_bin=/opt/homebrew/bin/brew
    [ -z "$brew_bin" ] && [ -x /usr/local/bin/brew ] && brew_bin=/usr/local/bin/brew
  fi

  # Load brew into this shell session so the rest of the script can use it.
  if [ -n "$brew_bin" ]; then
    eval "$("$brew_bin" shellenv)"
  elif [ "${DRY_RUN:-false}" != "true" ]; then
    error "Homebrew not found after install step"
    return 1
  fi
}

# Write a Brewfile to $1 from the _TAPS / _BREWS / _CASKS / _MAS working arrays
# (set by the wave functions below).
generate_brewfile() {
  local out="$1"
  {
    echo "# Generated by mac-setup — do not edit by hand."

    local item
    for item in "${_TAPS[@]:-}"; do
      [ -n "$item" ] && printf 'tap "%s"\n' "$item"
    done

    for item in "${_BREWS[@]:-}"; do
      [ -n "$item" ] && printf 'brew "%s"\n' "$item"
    done

    # Casks honor an optional install directory.
    local cask_args=""
    [ -n "${CASK_APPDIR:-}" ] && cask_args=", args: { appdir: \"${CASK_APPDIR}\" }"
    for item in "${_CASKS[@]:-}"; do
      [ -n "$item" ] && printf 'cask "%s"%s\n' "$item" "$cask_args"
    done

    # Mac App Store apps: entries are "Name|id"; mas is added implicitly.
    local has_mas=false name id
    for item in "${_MAS[@]:-}"; do
      [ -n "$item" ] || continue
      if [ "$has_mas" = false ]; then
        printf 'brew "mas"\n'
        has_mas=true
      fi
      name="${item%%|*}"
      id="${item##*|}"
      printf 'mas "%s", id: %s\n' "$name" "$id"
    done
  } >"$out"
}

# Generate a Brewfile from the current _TAPS/_BREWS/_CASKS/_MAS arrays and apply it.
# $1 = section label, $2 = filename suffix for the generated Brewfile.
_run_brew_bundle() {
  local label="$1" suffix="$2"

  if [ "${#_BREWS[@]}" -eq 0 ] && [ "${#_CASKS[@]}" -eq 0 ] && [ "${#_MAS[@]}" -eq 0 ]; then
    info "$label — nothing to install, skipping"
    return 0
  fi

  section "$label"

  local brewfile
  brewfile="$(pwd)/.Brewfile.$suffix"
  generate_brewfile "$brewfile"

  info "Generated Brewfile:"
  sed 's/^/      /' "$brewfile"

  # --jobs auto installs formulae in parallel (up to 4 cores); --verbose shows
  # per-step progress. HOMEBREW_VERBOSE surfaces download progress during fetch.
  HOMEBREW_VERBOSE=1 run brew bundle install --file="$brewfile" --jobs auto --verbose

  if [ "${DRY_RUN:-false}" != "true" ]; then
    rm -f "$brewfile"
  fi
}

# Wave 1: minimal tools needed to install and use the dotfiles (e.g. stow, the
# shell, the prompt font). Runs before the dotfiles step.
install_homebrew_essential() {
  _TAPS=( ${BREW_TAPS[@]+"${BREW_TAPS[@]}"} )
  _BREWS=( ${BREW_PACKAGES_ESSENTIAL[@]+"${BREW_PACKAGES_ESSENTIAL[@]}"} )
  _CASKS=( ${BREW_CASKS_ESSENTIAL[@]+"${BREW_CASKS_ESSENTIAL[@]}"} )
  _MAS=()
  _run_brew_bundle "Wave 1/2: essential tools (for dotfiles)" "essential"
}

# Wave 2: everything else — the heavier and optional tools and GUI apps. Runs
# after the dotfiles are in place.
install_homebrew_main() {
  _TAPS=( ${BREW_TAPS[@]+"${BREW_TAPS[@]}"} )
  _BREWS=( ${BREW_PACKAGES[@]+"${BREW_PACKAGES[@]}"} )
  _CASKS=( ${BREW_CASKS[@]+"${BREW_CASKS[@]}"} )
  _MAS=( ${MAS_APPS[@]+"${MAS_APPS[@]}"} )
  _run_brew_bundle "Wave 2/2: remaining tools and apps" "main"
}
