#!/usr/bin/env bash
# Homebrew: ensure it is installed and on PATH, then install everything declared
# in the config (taps, formulae, casks, Mac App Store apps) via `brew bundle`.

# Ensure Homebrew is installed and its environment is loaded into this shell.
ensure_homebrew() {
  if command -v brew >/dev/null 2>&1; then
    info "Homebrew already installed ($(command -v brew))"
  elif [ "${DRY_RUN:-false}" = "true" ]; then
    section "Installing Homebrew"
    # Don't fetch the installer over the network during a dry run.
    printf '%s  [dry-run] install Homebrew via the official install.sh%s\n' \
      "$_C_YELLOW" "$_C_RESET"
  else
    section "Installing Homebrew"
    NONINTERACTIVE=1 /bin/bash -c \
      "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  # Load brew into this shell session, picking the right prefix for the arch.
  local brew_bin=""
  if [ -x /opt/homebrew/bin/brew ]; then
    brew_bin=/opt/homebrew/bin/brew      # Apple Silicon
  elif [ -x /usr/local/bin/brew ]; then
    brew_bin=/usr/local/bin/brew         # Intel
  elif command -v brew >/dev/null 2>&1; then
    brew_bin="$(command -v brew)"
  fi

  if [ -n "$brew_bin" ]; then
    eval "$("$brew_bin" shellenv)"
  elif [ "${DRY_RUN:-false}" != "true" ]; then
    error "Homebrew not found after install step"
    return 1
  fi
}

# Write a Brewfile to $1 from the BREW_TAPS / BREW_PACKAGES / BREW_CASKS / MAS_APPS arrays.
generate_brewfile() {
  local out="$1"
  {
    echo "# Generated by mac-setup — do not edit by hand."

    local item
    for item in "${BREW_TAPS[@]:-}"; do
      [ -n "$item" ] && printf 'tap "%s"\n' "$item"
    done

    for item in "${BREW_PACKAGES[@]:-}"; do
      [ -n "$item" ] && printf 'brew "%s"\n' "$item"
    done

    # Casks honor an optional install directory.
    local cask_args=""
    [ -n "${CASK_APPDIR:-}" ] && cask_args=", args: { appdir: \"${CASK_APPDIR}\" }"
    for item in "${BREW_CASKS[@]:-}"; do
      [ -n "$item" ] && printf 'cask "%s"%s\n' "$item" "$cask_args"
    done

    # Mac App Store apps: config entries are "Name|id"; mas is added implicitly.
    local has_mas=false name id
    for item in "${MAS_APPS[@]:-}"; do
      [ -n "$item" ] || continue
      if [ "$has_mas" = false ]; then
        printf 'brew "mas"\n'
        has_mas=true
      fi
      name="${item%%|*}"
      id="${item##*|}"
      printf 'mas "%s", id: %s\n' "$name" "$id"
    done
  } >"$out"
}

# Generate a Brewfile and apply it.
install_homebrew_bundle() {
  section "Installing Homebrew packages, casks and App Store apps"

  local brewfile
  brewfile="$(pwd)/.Brewfile.generated"
  generate_brewfile "$brewfile"

  info "Generated Brewfile:"
  sed 's/^/      /' "$brewfile"

  run brew bundle install --file="$brewfile" --no-lock

  if [ "${DRY_RUN:-false}" != "true" ]; then
    rm -f "$brewfile"
  fi
}
